# -*- coding: utf-8 -*-
"""
Visible training entry point for the compiled GxE model.

Users can run this file directly after editing DEFAULT_ARGS below. Command-line
arguments are still supported and will override the defaults. For example:
    python run_train.py --trait PH --test_env DEH2_2017 --save_pred PH.csv
"""
import sys

DEFAULT_ARGS = {
    # Data directory. Graph raw files are expected under <root>/raw/.
    "--root": "/root/autodl-tmp/GAT/Maize/data/",
    "--env_file": "/root/autodl-tmp/GAT/Maize/data/raw/env.txt",
    "--pheno_file": "/root/autodl-tmp/GAT/Maize/data/raw/pheno.txt",

    # Graph raw file names. Use file names here, not absolute paths, when files are under <root>/raw/.
    "--a_file": "Maize_A.txt",
    "--edge_attr_file": "Maize_edge_attributes.txt",
    "--node_attr_file": "Maize_node_attributes.txt",
    "--sample_id_file": "sample_id.txt",
    "--node_per_graph": "2473",
    "--processed_file": "data.pt",
    "--force_reprocess": True,

    # Prediction task.
    "--trait": "Yield",
    "--split_mode": "env",
    "--test_env": "DEH1_2016",
    "--save_pred": "Yield.csv",

    # Training hyperparameters. These values can be replaced by --load_params best_params.json.
    "--batch_size": "128",
    "--lr": "0.00029927982772934",
    "--epochs": "200",
    "--hidden_channels": "256",
    "--num_layers": "4",
    "--dropout": "0.139046213354954",
    "--weight_decay": "1.98073109454762E-06",
    "--alpha": "0.959261698172542",
    "--beta": "0.0895801517257592",
    "--k_folds": "10",
    "--pca_dim": "64",
    "--patience": "20",
    "--seed": "123",

    # Optional: set this to a JSON file generated by tune_params.py.
    # Example: "--load_params": "best_params.json"
    "--load_params": None,
}

def dict_to_argv(arg_dict):
    argv = []
    for key, value in arg_dict.items():
        if isinstance(value, bool):
            if value:
                argv.append(key)
        elif value is None:
            continue
        else:
            argv.extend([key, str(value)])
    return argv

def main():
    import train_test
    default_argv = dict_to_argv(DEFAULT_ARGS)
    user_argv = sys.argv[1:]
    sys.argv = [sys.argv[0]] + default_argv + user_argv
    print("[INFO] Running training with arguments:")
    print(" ".join(sys.argv))
    train_test.main()

if __name__ == "__main__":
    main()
